### ISSUE TITLE
All methods imported in java file as “Primary”

### ISSUE THREAD

**Issue by AbhishekCompro** [AbhishekCompro/abhishekcompro.github.io#24]

**Comment by shiprabathla** [comment]
When we add a pathway it contains one method from each of selected item. Currently, those items can have different methods selected and thus one can't be shown in java. Some approach for this is yet to be finalized.

**Comment by AbhishekCompro** [comment]
Duplicate: https://github.com/AbhishekCompro/abhishekcompro.github.io/issues/83
