### ISSUE TITLE
breadcrumb is not updating as expected

### ISSUE THREAD

**Issue by AbhishekCompro** [AbhishekCompro/abhishekcompro.github.io#58]

**Comment by manishcompro** [comment]
Breadcrumb always show - Scenario T1 - Item 1 - Method 1 - Action 1.
It should only shows the node selected. If user has selected Method 1 in Left tree, it should show breadcrumb till Method 1.

**Comment by AbhishekCompro** [comment]
This issue was moved to sim5runner/sim5runner.github.io#14
