### ISSUE TITLE
Add sequence in Method Type while saving data

### ISSUE THREAD

**Issue by AbhishekCompro** [AbhishekCompro/abhishekcompro.github.io#62]
"http://prntscr.com/alew41"

Ref screenshot above: Suppose there are multiple methods in an item & method "Keyboard" is selected in more than one method. 

Then data saved will look like:
Method 1: Keyboard
Method 2: Keyboard (2)

**Comment by shiprabathla** [comment]
fixed.

**Comment by shiprabathla** [comment]
Closed
