### ISSUE TITLE
On deleting a Method of an Item shows Null in Add pathway

### ISSUE THREAD

**Issue by manishcompro** [AbhishekCompro/abhishekcompro.github.io#69]
On deleting a Method of an Item shows Null in Add pathway. It does not reset init flag to false
![image](https://cloud.githubusercontent.com/assets/3080585/14100086/6e604cf0-f5a8-11e5-8530-46cbafa7c81d.png)

**Comment by AbhishekCompro** [comment]
This issue was moved to sim5runner/sim5runner.github.io#50
