### ISSUE TITLE
Update Select Method Groups list

### ISSUE THREAD

**Issue by manishcompro** [AbhishekCompro/abhishekcompro.github.io#80]
Update Select Method Groups list as below
- Add all method type
- Primary

Remove Main & Alternate options

**Comment by shiprabathla** [comment]
fixed

**Comment by shiprabathla** [comment]
released on [stgsim5runner](https://github.com/stgsim5runner/stgsim5runner.github.io)

**Comment by shiprabathla** [comment]
Closed
